Repository kubevirt/csi-driver, pull requests merged in 2020-12, with the labels that each got.

#12 CNV-8303 Make it easy to create/configure service-accounts and secrets
  README.md
  deploy/030-node.yaml
  deploy/040-controller.yaml
  deploy/infra-cluster-service-account.yaml
  deploy/secret.yaml
Labels: approved, dco-signoff: yes, lgtm, size/M

#13 Introduce pkg/service test suite
  Makefile
  cmd/kubevirt-csi-driver/kubevirt-csi-driver.go
  go.mod
  go.sum
  pkg/kubevirt/client.go
  pkg/kubevirt/mocked_client.go
  pkg/service/controller.go
  pkg/service/driver.go
  pkg/service/node.go
  pkg/service/node_test.go
  pkg/service/server.go
  pkg/service/service_suite_test.go
  pkg/version.go
  vendor/github.com/golang/mock/gomock/call.go
  vendor/github.com/golang/mock/gomock/callset.go
  vendor/github.com/golang/mock/gomock/controller.go
  vendor/github.com/golang/mock/gomock/matchers.go
  vendor/modules.txt
Labels: approved, dco-signoff: yes, lgtm, size/XL

#15 CNV-8819 Enabling hotplug feature in Kubevirt
  README.md
  deploy/example/kubevirt-config.yaml
  deploy/example/kubevirt.yaml
Labels: dco-signoff: yes, do-not-merge/release-note-label-needed, size/M

#17 Fix order of namespace creation
  README.md
Labels: dco-signoff: yes, size/XS
