Repository kubevirt/csi-driver, pull requests merged in 2020-11, with the labels that each got.

#7 Contoller implementation fixes
  cmd/kubevirt-csi-driver/kubevirt-csi-driver.go
  pkg/kubevirt/client.go
  pkg/service/controller.go
  pkg/service/driver.go
  pkg/service/node.go
Labels: dco-signoff: yes, do-not-merge/release-note-label-needed, size/L

#8 Fix function getVolumeModeFromRequest.
  pkg/service/controller.go
Labels: approved, dco-signoff: yes, lgtm, size/XS

#11 build: build a dynamic binary and default to CGO_ENABLED
  Makefile
Labels: approved, dco-signoff: yes, lgtm, size/XS

#10 Unit tests for controller service
  pkg/service/controller_test.go
Labels: approved, dco-signoff: yes, lgtm, size/L

#9 Various cleanups
  Makefile
  cmd/kubevirt-csi-driver/kubevirt-csi-driver.go
  deploy/030-node.yaml
  deploy/040-controller.yaml
  pkg/kubevirt/client.go
  pkg/service/controller.go
Labels: approved, dco-signoff: yes, lgtm, size/L
