Repository kubevirt/csi-driver, pull requests merged in 2022-08, with the labels that each got.

#40 Change the image building to the standard way
  .dockerignore
  Dockerfile
  Makefile
  hack/cri-bin.sh
Labels: size/M, release-note-none, dco-signoff: yes, lgtm, approved

#42 Fix dockerfile typo
  Dockerfile
Labels: release-note-none, size/XS, dco-signoff: yes, lgtm, approved

#43 Increase linter timeout
  hack/run-linter.sh
Labels: release-note-none, size/XS, dco-signoff: yes, lgtm, approved

#45 Add ability to split Controller to infra cluster and Node to tenant cluster
  Dockerfile
  cmd/kubevirt-csi-driver/kubevirt-csi-driver.go
  deploy/030-node.yaml
  deploy/040-controller.yaml
  pkg/service/controller.go
  pkg/service/driver.go
  pkg/service/identity.go
  pkg/service/node.go
  pkg/service/service_suite_test.go
Labels: release-note, size/L, dco-signoff: yes, lgtm, approved

#48 Add mhenriks and brybacki as approvers
  OWNERS_ALIASES
Labels: release-note-none, size/XS, dco-signoff: yes, lgtm, approved

#47 Uses a builder container that exists in openshift builder dockerfile
  Dockerfile.openshift
Labels: release-note-none, size/XS, dco-signoff: yes, lgtm, approved

#49 Linter: bigger timeout
  hack/run-linter.sh
Labels: release-note-none, size/XS, dco-signoff: yes, lgtm, approved

#51 Add a test lane script
  hack/ci/e2e-latest.sh
Labels: release-note-none, size/XS, dco-signoff: yes, lgtm, approved

#52 Insecure registry
  Makefile
  hack/cri-bin.sh
  kubevirtci
Labels: size/S, release-note-none, dco-signoff: yes, lgtm, approved

#54 Compatibility with lsblk that does not support PATH colume
  pkg/service/node.go
Labels: release-note-none, size/XS, dco-signoff: yes, lgtm, approved
