Repository kubevirt/csi-driver, pull requests merged in 2022-09, with the labels that each got.

#58 remove openshift dockerfile
  Dockerfile.openshift
Labels: size/S, release-note-none, dco-signoff: yes, lgtm, approved

#61 [Clean-code]: Equal(true) => BeTrue()
  pkg/service/service_suite_test.go
Labels: release-note-none, size/XS, dco-signoff: yes, lgtm, approved, sig/code-quality

#60 Add script for E2E CI test, to check split cluster
  hack/ci/e2e-latest-split.sh
Labels: release-note-none, size/XS, dco-signoff: yes, lgtm, approved

#55 e2e tests
  e2e/create-pvc_test.go
Labels: release-note-none, size/L, dco-signoff: yes, lgtm, approved

#67 Remove unused CRD list/create rbac
  deploy/020-autorization.yaml
  deploy/split-infra-tenant/020-controller-authorization.yaml
Labels: release-note-none, size/XS, dco-signoff: yes, lgtm, approved

#63 Add kubernetes csi e2e function test suite.
  .gitignore
  hack/run-k8s-e2e.sh
  hack/test-driver.yaml
  kubevirtci
  pkg/service/controller.go
  pkg/service/controller_test.go
  pkg/service/node.go
  pkg/service/service_suite_test.go
Labels: release-note-none, size/L, dco-signoff: yes, lgtm, approved

#69 Mark DVs to be retained by cdi
  pkg/service/controller.go
Labels: release-note-none, size/XS, dco-signoff: yes, lgtm, approved
