Repository kubevirt/csi-driver, pull requests merged in 2022-11, with the labels that each got.

#62 Added an allow list for infra-stroage-class to volumes
  cmd/kubevirt-csi-driver/kubevirt-csi-driver.go
  deploy/040-controller.yaml
  deploy/split-infra-tenant/040-controller.yaml
  go.mod
  pkg/service/controller.go
  pkg/service/controller_test.go
  pkg/service/driver.go
  pkg/util/util.go
  sanity/sanity_suite_test.go
Labels: release-note, size/L, dco-signoff: yes, lgtm, approved

#75 Add release github action
  .github/workflows/create_image.yaml
  .github/workflows/create_release.yaml
Labels: size/M, release-note-none, dco-signoff: yes, lgtm, approved

#76 Fix the "Create and push image" github action
  .github/workflows/create_image.yaml
Labels: release-note-none, size/XS, dco-signoff: yes, lgtm, approved

#74 Support kustomize during deployment
  .gitignore
  README.md
  deploy/000-csi-driver.yaml
  deploy/000-namespace.yaml
  deploy/020-autorization.yaml
  deploy/030-node.yaml
  deploy/configmap-template.yaml
  deploy/configmap.yaml
  deploy/controller-infra/base/deploy.yaml
  deploy/controller-infra/base/kustomization.yaml
  deploy/controller-tenant/base/deploy.yaml
  deploy/controller-tenant/base/kustomization.yaml
  deploy/host-pod.yaml
  deploy/infra-cluster-kubeconfig-template.yaml
  deploy/secret-template.yaml
  deploy/split-infra-tenant/000-csi-driver.yaml
  deploy/split-infra-tenant/000-namespace.yaml
  deploy/split-infra-tenant/020-controller-authorization.yaml
  deploy/split-infra-tenant/020-node-authorization.yaml
  deploy/split-infra-tenant/030-node.yaml
  deploy/split-infra-tenant/configmap-template.yaml
  deploy/split-infra-tenant/infra-cluster-service-account.yaml
  deploy/tenant/base/deploy.yaml
  deploy/tenant/base/kustomization.yaml
  hack/cluster-sync-split.sh
  hack/cluster-sync.sh
  hack/cluster-up.sh
  hack/common.sh
  hack/create-infra-kubeconfig.sh
  kubevirtci
Labels: release-note, size/XXL, dco-signoff: yes, lgtm, approved
