Repository kubevirt/csi-driver, pull requests merged in 2024-04, with the labels that each got.

#106 Implement storage snapshot mapping
  README.md
  cmd/kubevirt-csi-driver/kubevirt-csi-driver.go
  deploy/tenant/base/deploy.yaml
  docs/snapshot-driver-config.md
  go.mod
  go.sum
  hack/cluster-sync-split.sh
  hack/cluster-sync.sh
  hack/common.sh
  pkg/generated/bindata.go
  pkg/kubevirt/client.go
  pkg/kubevirt/client_test.go
  pkg/service/controller.go
  pkg/service/controller_test.go
  pkg/service/identity.go
  pkg/util/util.go
  vendor/kubevirt.io/containerized-data-importer-api/pkg/apis/core/v1beta1/types.go
  vendor/kubevirt.io/containerized-data-importer-api/pkg/apis/core/v1beta1/types_swagger_generated.go
  vendor/kubevirt.io/containerized-data-importer-api/pkg/apis/core/v1beta1/zz_generated.deepcopy.go
  vendor/modules.txt
Labels: release-note, size/XXL, dco-signoff: yes, lgtm, approved

#108 Lazy load volume/snapshot mapping
  cmd/kubevirt-csi-driver/kubevirt-csi-driver.go
  hack/generate_clients.sh
  pkg/kubevirt/client.go
  pkg/kubevirt/client_test.go
Labels: release-note, size/L, dco-signoff: yes, lgtm, approved

#107 Allow RWX, FS infra PVC
  e2e/create-pvc_test.go
  hack/ci/deploy-infra-fs-sc.sh
  hack/ci/e2e-latest-split.sh
  hack/ci/e2e-latest.sh
  pkg/service/controller.go
  pkg/service/controller_test.go
Labels: release-note, size/L, dco-signoff: yes, lgtm, approved

#109 Fix default snapshot class allowed not working
  pkg/kubevirt/client.go
  pkg/kubevirt/client_test.go
Labels: size/S, release-note-none, dco-signoff: yes, lgtm, approved
