Repository kubevirt/csi-driver, pull requests merged in 2024-03, with the labels that each got.

#103 Address CVE-2024-1725
  Makefile
  cmd/kubevirt-csi-driver/kubevirt-csi-driver.go
  e2e/common_test.go
  e2e/create-pvc_test.go
  hack/cluster-sync.sh
  pkg/kubevirt/client.go
  pkg/kubevirt/client_test.go
  pkg/service/controller.go
Labels: release-note, size/L, dco-signoff: yes, lgtm, approved

#104 Remove usage of securityContext.privileged = true for snapshot container
  deploy/controller-infra/base/deploy.yaml
Labels: release-note-none, size/XS, dco-signoff: yes, lgtm, approved

#101 Don't use resource limits for controllers
  deploy/controller-infra/base/deploy.yaml
  deploy/tenant/base/deploy.yaml
Labels: size/S, release-note-none, dco-signoff: yes, lgtm, approved

#105 Get storage class from PVC for snapshot matching
  hack/common.sh
  pkg/kubevirt/client.go
  pkg/kubevirt/client_test.go
Labels: size/M, release-note-none, dco-signoff: yes, lgtm, approved
